language: c++
compiler: g++

matrix:
  include:
    - os: osx
      osx_image: xcode11.4

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install bison
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install re-flex
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install unittest-cpp

script:
  - make test
  - ./build/test

after_success:
  - make clean