language: c++
compiler: g++

matrix:
  include:
    - os: osx
      osx_image: xcode11.4

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install bison
  - export PATH="/usr/local/Cellar/bison/3.7.3/bin:$PATH"
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install re-flex
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install unittest-cpp

script:
  - mkdir build/
  - make ci
  - ./build/test

after_success:
  - make clean