language: c++
compiler: g++

matrix:
  include:
    - os: osx
      osx_image: xcode11.4

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install bison@3.7.3
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install reflex@3.0.1
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install unittest-cpp@2.0.0

script:
  - make test
  - ./build/test

after_success:
  - make clean